### ISSUE TITLE
Typo in `/etc/yum.repos.d`?

### ISSUE THREAD

**Issue by travier** [LorbusChris/butane-config-template#1]
https://github.com/LorbusChris/butane-config-template/blob/4af9d777fbbcc04c5b89d26862ec2e1b18367bfa/config/10_os-extensions.bu#L77

`/etc/yum.repos.d` < without the `e`

**Comment by travier** [comment]
You might want to do something like https://discussion.fedoraproject.org/t/simplifying-updates-for-rpm-fusion-packages-and-other-packages-shipping-their-own-rpm-repos/30364 instead too but it is more complex

**Comment by LorbusChris** [comment]
I forgot to fix this before pushing to GH, thanks for catching that!

I don't really want to run rpm-ostree twice in order to do be able to overlay an RPM from rpmfusion, although that should certainly be possible, too.

I'm planning on making use of butane's tree functionality here, so I don't have to inline the files, or include them each by reference, which'll make it easier to manage them.
